### ISSUE TITLE
How to change height of ang-jsonedior 

### ISSUE THREAD

**Issue by SwapnilChidrawar** [mariohmol/ang-jsoneditor#8]
@mariohmol  HI.. I am using ang-jsoneditor along with angular 5. here now everything works perfectly but i wanted to change the height for my editor which I am opening in code mode. Can anybody have solution for it ?

**Comment by agborkowski** [comment]
im searching solutions too :) i think check css properties...

**Comment by niteshkatare** [comment]
Even I am looking for the solution for height issue.

**Comment by agborkowski** [comment]
works too:

```css
:host ::ng-deep json-editor,
:host ::ng-deep json-editor .jsoneditor,
:host ::ng-deep json-editor > div,
:host ::ng-deep json-editor jsoneditor-outer {
  height: 100%;
}
```
